/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Patient;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.Doctor;
import model.DoctorDirectory;
import model.Encounter;
import model.EncounterHistory;
import model.Hospital;
import model.HospitalDirectory;
import model.Patient;
import model.VitalSigns;
import ui.HomeFrame;

/**
 *
 * @author varshareddykumbham
 */
public class PatientPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientPanel
     */
    EncounterHistory encounterHistory;
    DefaultTableModel getDoctorsTblModel;
    DefaultTableModel tblEncounterModel;
    ArrayList<String> hospitalNames;
    String patientId;
    Patient patient;
    public PatientPanel(Patient p) {
        initComponents();
        patient = p;
        patientId = p.getId();
        encounterHistory = p.getEncounterHistory();
        tfPatientName.setText(p.getName());
        tfCommunityName.setText(p.getCommunity());
        
        getDoctorsTblModel = (DefaultTableModel)tableGetDoctors.getModel();
        tblEncounterModel = (DefaultTableModel) tableGetEncounterHistory.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPatientName = new javax.swing.JLabel();
        jLabelCommunity = new javax.swing.JLabel();
        tfPatientName = new javax.swing.JTextField();
        tfCommunityName = new javax.swing.JTextField();
        btnGetDoctors = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGetDoctors = new javax.swing.JTable();
        btnLogout = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableGetEncounterHistory = new javax.swing.JTable();
        btnGetEncounterHistory = new javax.swing.JButton();
        btnBookAppointment = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEncounterID = new javax.swing.JTextField();
        dcEncounterDate = new com.toedter.calendar.JDateChooser();
        lblEncounterDoctorName = new javax.swing.JLabel();
        tfDoctorName = new javax.swing.JTextField();

        jLabelPatientName.setText("Patient Name");

        jLabelCommunity.setText("Community");

        tfPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPatientNameActionPerformed(evt);
            }
        });

        tfCommunityName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCommunityNameActionPerformed(evt);
            }
        });

        btnGetDoctors.setText("Get Doctors");
        btnGetDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetDoctorsActionPerformed(evt);
            }
        });

        tableGetDoctors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor Name", "Doctor Id", "Gender", "Hospital Name", "Department", "Phone Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableGetDoctors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableGetDoctorsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableGetDoctors);

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        tableGetEncounterHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Encounter Id", "Encounter Date", "Temperature", "BP", "Heart Rate", "Doctor"
            }
        ));
        jScrollPane2.setViewportView(tableGetEncounterHistory);

        btnGetEncounterHistory.setText("Get Encounter History");
        btnGetEncounterHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetEncounterHistoryActionPerformed(evt);
            }
        });

        btnBookAppointment.setText("Book Appointment");
        btnBookAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookAppointmentActionPerformed(evt);
            }
        });

        jLabel1.setText("Encounter ID");

        jLabel2.setText("Encounter Date");

        dcEncounterDate.setDateFormatString("dd-MM-yyyy");

        lblEncounterDoctorName.setText("Doctor Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEncounterID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dcEncounterDate, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblEncounterDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfDoctorName)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnBookAppointment)
                                    .addComponent(btnGetEncounterHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPatientName)
                                    .addComponent(jLabelCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfCommunityName, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnGetDoctors))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPatientName)
                            .addComponent(tfPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCommunity)
                            .addComponent(tfCommunityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnGetDoctors))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEncounterID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(dcEncounterDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEncounterDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBookAppointment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGetEncounterHistory)
                        .addGap(115, 115, 115))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPatientNameActionPerformed

    private void tfCommunityNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCommunityNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCommunityNameActionPerformed

    private void btnGetDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetDoctorsActionPerformed
        // TODO add your handling code here:

        String communityName = tfCommunityName.getText();
        hospitalNames = new ArrayList();
        System.out.println(HospitalDirectory.getHospitals());
        for(Hospital hospital:HospitalDirectory.getHospitals()) {
            if(hospital.getCommunity().equals(communityName)) {
                hospitalNames.add(hospital.getHospitalName());
            }
        }
        System.out.println(hospitalNames);
        for(Doctor doctor:DoctorDirectory.getDoctors()) {
            String hospitalName = doctor.getHospitalName();
            if(hospitalNames.contains(hospitalName)) {
                Object[] data = {doctor.getName(), doctor.getId(), doctor.getGender(),
                    doctor.getHospitalName(), doctor.getHospitalDepartment(), doctor.getPhoneNumber()};
                getDoctorsTblModel.addRow(data);
            }
        }

    }//GEN-LAST:event_btnGetDoctorsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        JFrame patientFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        patientFrame.dispose();
        HomeFrame hf = new HomeFrame();
        hf.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnGetEncounterHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetEncounterHistoryActionPerformed
        // TODO add your handling code here:
        //String patientId = txtEnterPatientId.getText();
        tblEncounterModel.setRowCount(0);
        for (Encounter en : encounterHistory.getEncounters()) {
            SimpleDateFormat dateformat = new SimpleDateFormat("dd-MM-yyyy");
            String date = dateformat.format(en.getEncounterDate());
            Object[] data = {en.getEncounterId(), date,
                en.getVitalSigns().getTemperature(), en.getVitalSigns().getBloodPressure(),
                en.getVitalSigns().getHeartRate(), en.getDoctorName()};
            tblEncounterModel.addRow(data);
            System.out.println(en.getPatientId());                    
                    }
        
    }//GEN-LAST:event_btnGetEncounterHistoryActionPerformed

    private void btnBookAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookAppointmentActionPerformed
        // TODO add your handling code here:
        VitalSigns vitalSigns = new VitalSigns();
        String encounterId = txtEncounterID.getText(); 
        String doctorName = tfDoctorName.getText();
        Date encounterDate = dcEncounterDate.getDate();
        Encounter e = new Encounter(encounterId, patient.getName(), patient.getAge(), patient.getId(), vitalSigns, 
             doctorName, encounterDate);
        patient.getEncounterHistory().getEncounters().add(e);
        
        
    }//GEN-LAST:event_btnBookAppointmentActionPerformed

    private void tableGetDoctorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableGetDoctorsMouseClicked
        // TODO add your handling code here:
        int row = tableGetDoctors.getSelectedRow();        
        String doctorName = getDoctorsTblModel.getValueAt(row, 0).toString();
        tfDoctorName.setText(doctorName);
    }//GEN-LAST:event_tableGetDoctorsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookAppointment;
    private javax.swing.JButton btnGetDoctors;
    private javax.swing.JButton btnGetEncounterHistory;
    private javax.swing.JButton btnLogout;
    private com.toedter.calendar.JDateChooser dcEncounterDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCommunity;
    private javax.swing.JLabel jLabelPatientName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEncounterDoctorName;
    private javax.swing.JTable tableGetDoctors;
    private javax.swing.JTable tableGetEncounterHistory;
    private javax.swing.JTextField tfCommunityName;
    private javax.swing.JTextField tfDoctorName;
    private javax.swing.JTextField tfPatientName;
    private javax.swing.JTextField txtEncounterID;
    // End of variables declaration//GEN-END:variables
}
