import java.awt.Image;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author varshareddykumbham
 */
public class DisplayJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayJPanel
     */
    Employee emp;
    String chosenImagePath;
    public DisplayJPanel(Employee emp) {
        initComponents();
        this.emp = emp;
        displayEmployeeDetails();
    }
    
    public void displayEmployeeDetails(){
        
       DefaultTableModel tblModel = (DefaultTableModel)tableEmployees.getModel();
       ArrayList<Employee> empObjs = CreateJPanel.empObjs;
       for(Employee employee: empObjs) {
           String name = employee.getName();
           String employeeId = employee.getEid();
           int age = employee.getAge();
           String gender = employee.getGender();
           String startDate = employee.getStartDate();
           String level = employee.getLevel();
           String teamInfo = employee.getTeamInfo();
           String positionTitle = employee.getPositionTitle();
           String cellPhone = employee.getCellPhone();
           String email = employee.getEmail();
           String imageUrl = employee.getEmployeeImageUrl();
           
           Object[] data = {name, employeeId, age, gender,startDate, level, teamInfo, positionTitle, cellPhone, email, imageUrl};
           tblModel.addRow(data);
             
       }
       } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGenderGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEmployees = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        tfName = new javax.swing.JTextField();
        jLabelName = new javax.swing.JLabel();
        jLabelEmployeeId = new javax.swing.JLabel();
        tfEmployeeId = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabelCellPhone = new javax.swing.JLabel();
        tfCellPhone = new javax.swing.JTextField();
        btnView = new javax.swing.JButton();
        tfName_update = new javax.swing.JTextField();
        jLabelName_update = new javax.swing.JLabel();
        jLabelEmployeeId1 = new javax.swing.JLabel();
        tfEmployeeId_update = new javax.swing.JTextField();
        jLabelAge = new javax.swing.JLabel();
        tfAge = new javax.swing.JTextField();
        jLabelGender = new javax.swing.JLabel();
        rdMale = new javax.swing.JRadioButton();
        rdFemale = new javax.swing.JRadioButton();
        jLabelStartDate = new javax.swing.JLabel();
        jLabelLevel = new javax.swing.JLabel();
        tfLevel = new javax.swing.JTextField();
        jLabelTeamInfo = new javax.swing.JLabel();
        tfTeamInfo = new javax.swing.JTextField();
        jLabelPositionTitle = new javax.swing.JLabel();
        tfPositionTitle = new javax.swing.JTextField();
        jLabelContactInfo = new javax.swing.JLabel();
        jLabelCellPhone1 = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        tfCellPhone_update = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        btnUploadPhoto = new javax.swing.JButton();
        jLabelPhoto = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jStartDate = new com.toedter.calendar.JDateChooser();
        jLabelEmpImage = new javax.swing.JLabel();

        tableEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Employee ID", "Age", "Gender", "Start Date", "Level", "Team Info", "Position Title", "Cell Phone", "Email", "Photo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableEmployees);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        jLabelName.setText("Name");

        jLabelEmployeeId.setText("Employee Id");

        tfEmployeeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmployeeIdActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabelCellPhone.setText("Cell Phone");

        tfCellPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCellPhoneActionPerformed(evt);
            }
        });

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        tfName_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfName_updateActionPerformed(evt);
            }
        });

        jLabelName_update.setText("Name");

        jLabelEmployeeId1.setText("Employee Id");

        tfEmployeeId_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmployeeId_updateActionPerformed(evt);
            }
        });

        jLabelAge.setText("Age");

        tfAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAgeActionPerformed(evt);
            }
        });

        jLabelGender.setText("Gender");

        btnGenderGroup.add(rdMale);
        rdMale.setText("Male");
        rdMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdMaleActionPerformed(evt);
            }
        });

        btnGenderGroup.add(rdFemale);
        rdFemale.setText("Female");

        jLabelStartDate.setText("Start Date");

        jLabelLevel.setText("Level");

        tfLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLevelActionPerformed(evt);
            }
        });

        jLabelTeamInfo.setText("Team Info");

        tfTeamInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTeamInfoActionPerformed(evt);
            }
        });

        jLabelPositionTitle.setText("Position Title");

        tfPositionTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPositionTitleActionPerformed(evt);
            }
        });

        jLabelContactInfo.setText("Contact Info");

        jLabelCellPhone1.setText("Cell Phone");

        jLabelEmail.setText("Email");

        tfCellPhone_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCellPhone_updateActionPerformed(evt);
            }
        });

        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });

        btnUploadPhoto.setText("Upload Photo");
        btnUploadPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadPhotoActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCellPhone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCellPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(703, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabelPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelName_update, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 904, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelContactInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelLevel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelTeamInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelPositionTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelGender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfEmployeeId_update, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfName_update, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfLevel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                    .addComponent(tfTeamInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                    .addComponent(tfPositionTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdMale)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdFemale))
                                    .addComponent(jStartDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelEmployeeId1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelAge, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(38, 38, 38)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCellPhone1)
                                    .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfCellPhone_update, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(btnUploadPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelEmpImage, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(btnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(157, 157, 157))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmployeeId)
                    .addComponent(tfEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCellPhone)
                    .addComponent(tfCellPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName_update)
                    .addComponent(tfName_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmployeeId1)
                    .addComponent(tfEmployeeId_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAge)
                    .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGender)
                    .addComponent(rdMale)
                    .addComponent(rdFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelStartDate)
                    .addComponent(jStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 91, Short.MAX_VALUE)
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(552, 552, 552))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPositionTitle)
                            .addComponent(tfLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTeamInfo)
                            .addComponent(tfTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLevel)
                            .addComponent(tfPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addComponent(jLabelContactInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelCellPhone1)
                            .addComponent(tfCellPhone_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEmail)
                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabelEmpImage, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUploadPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(137, 137, 137)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        tfName_update.setEditable(true);
        tfEmployeeId_update.setEditable(false);
        tfAge.setEditable(true);
        jStartDate.setEnabled(true);
        tfLevel.setEditable(true);
        tfPositionTitle.setEditable(true);
        tfCellPhone_update.setEditable(true);
        tfEmail.setEditable(true);
        tfTeamInfo.setEditable(true);
        rdMale.setEnabled(true);
        rdFemale.setEnabled(true);
        btnUploadPhoto.setEnabled(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        ArrayList<Employee> empObjs = CreateJPanel.empObjs;
        int row = tableEmployees.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tableEmployees.getModel();
        model.removeRow(row);
        empObjs.remove(row);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void tfEmployeeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmployeeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmployeeIdActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String nameSearch = tfName.getText();
        String eidSearch = tfEmployeeId.getText();
        String cellPhoneSearch = tfCellPhone.getText();
        
        ArrayList<Employee> filteredEmployees = new ArrayList<Employee>();
        for(Employee emp: CreateJPanel.empObjs){
            
            
                
            if((emp.getName().equals(nameSearch) && 
                    emp.getEid().equals(eidSearch) && 
                    emp.getCellPhone().equals(cellPhoneSearch)) ||
                    
                    (emp.getName().equals(nameSearch) && 
                    emp.getEid().equals(eidSearch)) ||
                    
                    (emp.getEid().equals(eidSearch) && 
                    emp.getCellPhone().equals(cellPhoneSearch)) ||
                    
                    (emp.getName().equals(nameSearch) && 
                    emp.getCellPhone().equals(cellPhoneSearch)) ||
                    
                    emp.getName().equals(nameSearch) ||
                    emp.getEid().equals(eidSearch) ||
                    emp.getCellPhone().equals(cellPhoneSearch)) {
                filteredEmployees.add(emp);
            }
            
        }
        
        DefaultTableModel dm = (DefaultTableModel) tableEmployees.getModel();
        int rowCount = dm.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
        
        DefaultTableModel tblModel = (DefaultTableModel)tableEmployees.getModel();
        for(Employee emp: filteredEmployees){
            tblModel.addRow(new Object[]{
                emp.getName(),
                emp.getEid(),
                emp.getAge(),
                emp.getGender(),
                emp.getStartDate(),
                emp.getLevel(),
                emp.getTeamInfo(),
                emp.getPositionTitle(),
                emp.getCellPhone(),
                emp.getEmail(),
                emp.getEmployeeImageUrl()});
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tfCellPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCellPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCellPhoneActionPerformed

    private void tfName_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfName_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfName_updateActionPerformed

    private void tfEmployeeId_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmployeeId_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmployeeId_updateActionPerformed

    private void tfAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAgeActionPerformed

    private void rdMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdMaleActionPerformed

    private void tfLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLevelActionPerformed

    private void tfTeamInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTeamInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTeamInfoActionPerformed

    private void tfPositionTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPositionTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPositionTitleActionPerformed

    private void tfCellPhone_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCellPhone_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCellPhone_updateActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void btnUploadPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadPhotoActionPerformed
        JFileChooser l_ImageChooser = new JFileChooser();
        l_ImageChooser.setCurrentDirectory(new File("user.dir"));

        FileNameExtensionFilter imageExtensions = new FileNameExtensionFilter(" All Pic", "png", "jpeg","jpg","gif");
        l_ImageChooser.addChoosableFileFilter(imageExtensions);

        int a = l_ImageChooser.showSaveDialog(null);
        if(a == JFileChooser.APPROVE_OPTION)
        {
            File f = l_ImageChooser.getSelectedFile();
            chosenImagePath = f.getAbsolutePath();
            ImageIcon chosenImage = new ImageIcon(chosenImagePath);
            Image l_image = chosenImage.getImage().getScaledInstance(jLabelEmpImage.getWidth(),
                jLabelEmpImage.getHeight(), Image.SCALE_SMOOTH);
            jLabelEmpImage.setIcon(new ImageIcon(l_image));
        }
    }//GEN-LAST:event_btnUploadPhotoActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        int row = tableEmployees.getSelectedRow();
                
        try {
            TableModel model = tableEmployees.getModel();
            String name = model.getValueAt(row, 0).toString();
            String empid = model.getValueAt(row, 1).toString();
            String age = model.getValueAt(row, 2).toString();
            String gender = model.getValueAt(row, 3).toString();
            String startDate = model.getValueAt(row, 4).toString();
            String level = model.getValueAt(row, 5).toString();
            String teamInfo = model.getValueAt(row, 6).toString();
            String positionTitle = model.getValueAt(row, 7).toString();
            String phNo = model.getValueAt(row, 8).toString();
            String emailid = model.getValueAt(row, 9).toString();
            String imageUrl = model.getValueAt(row, 10).toString();
            tfName_update.setText(name);
            tfName_update.setEditable(false);
            tfEmployeeId_update.setText(empid);
            tfEmployeeId_update.setEditable(false);
            tfAge.setText(age);
            tfAge.setEditable(false);
              
            Date startDate_str=new SimpleDateFormat("dd-MM-yyyy").parse(startDate);
            jStartDate.setDate(startDate_str);
            jStartDate.setEnabled(true);
            
            tfLevel.setText(level);
            tfLevel.setEditable(false);
            tfPositionTitle.setText(positionTitle);
            tfPositionTitle.setEditable(false);
            tfCellPhone_update.setText(phNo);
            tfCellPhone_update.setEditable(false);
            tfEmail.setText(emailid);
            tfEmail.setEditable(false);
            tfTeamInfo.setText(teamInfo);
            tfTeamInfo.setEditable(false);
            btnUploadPhoto.setEnabled(false);
            if(gender.equalsIgnoreCase("male")){
                rdMale.setSelected(true);
            }
            else{
                rdFemale.setSelected(true);
            }
            rdMale.setEnabled(false);
            rdFemale.setEnabled(false);
            
            ImageIcon chosenImage = new ImageIcon(imageUrl);
            Image l_image = chosenImage.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
            jLabelEmpImage.setIcon(new ImageIcon(l_image));
        }
        catch(Exception ex) {
            if(row==-1) {
                JOptionPane.showMessageDialog(this,
                            "Please Select a row",
                            "Try Again",
                            JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String name = tfName_update.getText();
        String empId = tfEmployeeId_update.getText();
        int age = Integer.parseInt(tfAge.getText());
        rdMale.setActionCommand("Male");
        rdFemale.setActionCommand("Female");
        String gender = btnGenderGroup.getSelection().getActionCommand();
        
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyy");  
        String startDate = dateFormat.format(jStartDate.getDate());
        
        String level = tfLevel.getText();
        String teamInfo = tfTeamInfo.getText();
        String positionTitle = tfPositionTitle.getText();
        String phoneNo = tfCellPhone_update.getText();
        String emailId = tfEmail.getText();
        String imgUrl = chosenImagePath;
        
        DefaultTableModel tableModel = (DefaultTableModel) tableEmployees.getModel();
        int row = tableEmployees.getSelectedRow();
        tableModel.removeRow(row);
        Object[] empData = {name, empId, age, gender, startDate, level, teamInfo, 
        positionTitle, phoneNo, emailId, imgUrl};
        tableModel.insertRow(row, empData);
        
        ArrayList <Employee> empList = CreateJPanel.empObjs;
        Employee updatedEmp = new Employee(name, empId, age, gender, startDate, level, 
            teamInfo, positionTitle, phoneNo, emailId, imgUrl);
        for(Employee emp : empList) {
            if(emp.getEid().equals(empId)){
                int index = empList.indexOf(emp);
                empList.remove(index);
                empList.add(index, updatedEmp);
                break;
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.ButtonGroup btnGenderGroup;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUploadPhoto;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelCellPhone;
    private javax.swing.JLabel jLabelCellPhone1;
    private javax.swing.JLabel jLabelContactInfo;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEmpImage;
    private javax.swing.JLabel jLabelEmployeeId;
    private javax.swing.JLabel jLabelEmployeeId1;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelLevel;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelName_update;
    private javax.swing.JLabel jLabelPhoto;
    private javax.swing.JLabel jLabelPositionTitle;
    private javax.swing.JLabel jLabelStartDate;
    private javax.swing.JLabel jLabelTeamInfo;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jStartDate;
    private javax.swing.JRadioButton rdFemale;
    private javax.swing.JRadioButton rdMale;
    private javax.swing.JTable tableEmployees;
    private javax.swing.JTextField tfAge;
    private javax.swing.JTextField tfCellPhone;
    private javax.swing.JTextField tfCellPhone_update;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEmployeeId;
    private javax.swing.JTextField tfEmployeeId_update;
    private javax.swing.JTextField tfLevel;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfName_update;
    private javax.swing.JTextField tfPositionTitle;
    private javax.swing.JTextField tfTeamInfo;
    // End of variables declaration//GEN-END:variables
}
